#!/bin/bash

NIX_FLAGS=(
  --extra-experimental-features "flakes nix-command"
  --no-warn-dirty
)
HM_FLAGS=(
  --extra-experimental-features "flakes nix-command"
  -j auto
)
OFFLINE='y'

flag="$1"; shift
operation=""

while true; do
  case "$flag" in
    update)
      nix flake update
      pushd ./nix/home && nix run ".#nvfetcher" && popd
      ./update.sh
      exit 0
      ;;
    s|sw|switch)
      operation="switch"
      home=$1; shift
      HM_FLAGS+=( --flake ".#$home" )
      flag="exit"
      ;;
    expire|clean|expire-generations)
      operation="expire-generations"
      flag="exit"
      ;;
    l|list|generations)
      operation="generations"
      flag="exit"
      ;;
    --show-trace)
      HM_FLAGS+=( --show-trace )
      flag="$1"
      shift 1
      ;;
    --online|-u)
      OFFLINE='n'
      flag="$1"
      shift 1
      ;;
    exit)
      break
      ;;
    *)
      operation="$flag"
      break
  esac
done

if [ "$OFFLINE" = 'y' ]; then
  NIX_FLAGS+=( --offline )
  HM_FLAGS+=( --no-substitute )
  echo "Running in offline mode"
else
  nix flake update
fi

if (( $HM_DEBUG )); then
  echo "NIX_FLAGS: ${NIX_FLAGS[@]}"
  echo "HM_FLAGS: ${HM_FLAGS[@]}"
  echo "Operation: $operation"
  echo "Args: $@"
fi

nix "${NIX_FLAGS[@]}" run '.#home-manager' -- "${HM_FLAGS[@]}" $operation $@
