#!/bin/bash

operation=$1; shift
[[ -z "$operation" ]] \
  && echo "Missing operation" \
  && exit 1

NIX_FLAGS=(
  --extra-experimental-features "flakes nix-command"
)
HM_FLAGS=(
  --extra-experimental-features "flakes nix-command"
  --show-trace
)

case $operation in
  s|sw|switch)
    operation="switch"
    home=$1; shift
    HM_FLAGS+=( --flake ".?submodules=1#$home" )
    ;;
  *)
    ;;
esac

nix "${NIX_FLAGS[@]}" run .#home-manager -- "${HM_FLAGS[@]}" "$operation" "$@"
