format = """
$username\
$hostname\
$shlvl\
$singularity\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$nix_shell\
$memory_usage\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

command_timeout=80
[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold yellow)"
[git_branch]
symbol=" "
[git_status]
conflicted = ""
ahead = ""
behind = ""
diverged = "ﮙ"
untracked = ""
stashed = ""
modified = ""
staged = '[ $count](green) '
renamed = "凜"
deleted = ""
[jobs]
symbol=""
format="[$symbol]($style) "
