[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
[golang]
symbol=" "
[rust]
symbol=""
format="[$symbol ver ($version )]($style)"
[cmake]
symbol=" "
[git_branch]
symbol=" "
[git_status]
conflicted = " "
ahead = " "
behind = " "
diverged = "ﮙ "
untracked = " "
stashed = " "
modified = " "
staged = '[\( $count staged\)](green) '
renamed = "凜"
deleted = " "
[jobs]
symbol=""
format="[$symbol]($style) "
[package]
format = "pack [ $version](208 bold) "
