gui:
  theme:
    activeBorderColor:
      - yellow
      - bold
    inactiveBorderColor:
      - white
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

keybinding:
  universal:
    nextMatch: '='
    prevMatch: '-'
