use_nerdfont=false
notify=true
audio_cache_size=2000
[theme]
background = ""
primary = "#DCD7BA"
secondary = "#2D4F67"
title = "#E6C384"
playing = "#DCD7BA"
playing_selected = "#98BB6C"
playing_bg = "#76946A"
highlight = "#DCD7BA"
highlight_bg = "#9c9c9c"
error = "#DCD7BA"
error_bg = "#E83C3C"
statusbar = "#DCD7BA"
statusbar_progress = "#00AC4C"
statusbar_bg = ""
cmdline = "#DCD7BA"
cmdline_bg = "#16161D"
