gui:
  theme:
    activeBorderColor:
      - white
      - bold
    inactiveBorderColor:
      - magenta
keybinding:
  universal:
    nextMatch: '='
    prevMatch: '-'
  branches:
    setUpstream: 's'
