gui:
  theme:
    activeBorderColor:
      - yellow
      - bold
    inactiveBorderColor:
      - white
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
keybinding:
  universal:
    nextMatch: '='
    prevMatch: '-'
  branches:
    setUpstream: 's'

customCommands:
  - key: '<c-p>'
    context: 'global'
    loadingText: 'pushing'
    description: 'push to specific branch and remote'
    prompts:
      - type: 'input'
        title: 'push to which remote?'
      - type: 'input'
        title: 'push to which branch?'
    command: 'git push {{index .PromptResponses 0}} {{index .PromptResponses 1}}'
  - key: 'C'
    command: 'git commit -v'
    description: 'commit file with editor and with diff'
    context: 'files'
    subprocess: true
