[window]
opacity = 1
#blur = true
decorations = "Transparent"
startup_mode = "Fullscreen"
dynamic_padding = true

[window.padding]
x = 3
y = 3

[font]
normal = { family = "monospace", style = "Regular" }
size = 9

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
