#!/bin/sh

[[ -z "$@" ]] && exit 1

initiate() {
  local path=$1; shift
  local dir=$(dirname $path)

  mkdir -p $dir
  echo "Initiated directory $dir"
  touch $path
  echo "Created file $path"
}

for input in $@; do
  initiate $input
done
