#!/bin/sh

# randomly pick background
gen_picture() {
  echo "${HOME}/Pictures/Anime/$(ls $HOME/Pictures/Anime | sort -R | tail -1)"
}

# setup background
swaybg \
  -o eDP-1 \
  -m fill -i $(gen_picture) \
  -o HDMI-A-1 \
  -m fill -i $(gen_picture)
