# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  neovim-nightly = {
    pname = "neovim-nightly";
    version = "nightly";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "neovim";
      rev = "nightly";
      fetchSubmodules = false;
      sha256 = "sha256-0vixi70e4yS2ZKkAFTnjD3sCKAI5GnRJf5Biz2sNCn0=";
    };
  };
  nvim = {
    pname = "nvim";
    version = "f3a480a14eecccc643479d1953f259d86c4b402a";
    src = fetchFromGitHub {
      owner = "Avimitin";
      repo = "nvim";
      rev = "f3a480a14eecccc643479d1953f259d86c4b402a";
      fetchSubmodules = false;
      sha256 = "sha256-x5OBOtuL7QEoSu0TIXQK8zxTtMPfE9p65F/U0kM3tMw=";
    };
    date = "2024-03-06";
  };
}
