# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  neovim-nightly = {
    pname = "neovim-nightly";
    version = "nightly";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "neovim";
      rev = "nightly";
      fetchSubmodules = false;
      sha256 = "sha256-0vixi70e4yS2ZKkAFTnjD3sCKAI5GnRJf5Biz2sNCn0=";
    };
  };
  nvim = {
    pname = "nvim";
    version = "07da33442e68aa3c37ebbfd4b92fc76a9c76e223";
    src = fetchFromGitHub {
      owner = "Avimitin";
      repo = "nvim";
      rev = "07da33442e68aa3c37ebbfd4b92fc76a9c76e223";
      fetchSubmodules = false;
      sha256 = "sha256-3kCjSYxjHV9cYDx33Fnnx1Ni79y65ctXjAiK2FOr1T4=";
    };
    date = "2024-04-17";
  };
}
