# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim = {
    pname = "nvim";
    version = "5af7b9e9b4cf1f11bff871b15c79ee735cfdb424";
    src = fetchFromGitHub {
      owner = "Avimitin";
      repo = "nvim";
      rev = "5af7b9e9b4cf1f11bff871b15c79ee735cfdb424";
      fetchSubmodules = false;
      sha256 = "sha256-jD95hoeN8NWkQaD+LOb2Ud9DDZz73WWAZSWtzl9FmKA=";
    };
    date = "2024-01-26";
  };
}
