#!/usr/bin/env sh

if ! command -v neovide > /dev/null; then
  echo "This plugin is for neovide, please install it first"
  exit 1
fi

if ! command -v nvr > /dev/null; then
  echo "This plugin relies on nvr, please install it by:"
  echo "pip install neovim-remote"
  exit 1
fi

if test -z $1; then
  echo "No file input"
  exit 1
fi

if ! nvr --nostart -s --remote $1; then
  NVIM_LISTEN_ADDRESS=/tmp/nvimsocket neovide $1
fi
